BurgerNymy/BurgerNymy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from . import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('burgers.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""
www.site.com/admin/
www.site.com
www.site.com/about/
www.site.com/home/
www.site.com/catalog/






"""

BurgerNymy/carts/urls.py
# goods/urls.py

from django.urls import path
from carts import views

app_name = "carts"
urlpatterns = [
    path("cart_add/", views.cart_add, name="cart_add"),
    path("cart_change/", views.cart_change, name="cart_change"),
    path("cart_remove/", views.cart_remove, name="cart_remove"),
]

BurgerNymy/goods/urls.py
# goods/urls.py

from django.urls import path
from goods import views

app_name = "goods"
urlpatterns = [
    path("search/", views.catalog, name="search"),
    path("<slug:category_slug>/", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product"),

]

BurgerNymy/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path("create_order/", views.create_order, name="create_order"),
    ]

BurgerNymy/users/urls.py
# burgers/urls.py

from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name='registration'),
    path("profile/", views.profile, name='profile'),
    path("logout/", views.logout, name='logout'),
    path("users_cart/", views.users_cart, name='users_cart'),

    # Add other paths as needed
]

BurgerNymy/users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='profile_image')
    phone_number = models.CharField(max_length=10, blank=True, null=True)
    class Meta:
        db_table = 'user'
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.username

BurgerNymy/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from .models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta():
        model = User
        fields = [
            'username', 'password',
        ]

class UserRegistrationForm(UserCreationForm):
    class Meta():
        model = User
        fields=[
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",

        ]
        first_name = forms.CharField()
        last_name = forms.CharField()
        username = forms.CharField()
        email = forms.CharField()
        password1 = forms.CharField()
        password2 = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta():
        model = User
        fields = [
            "image",
            "first_name",
            "last_name",
            "username",
            "email",
        ]
    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

BurgerNymy/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth, messages
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from carts.models import Cart
from orders.models import Order, OrderItem
from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                messages.success(request, f"{username}, Logged in 👏🏻")

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)
                redirect_page = request.POST.get('next', None)

                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:home'))

    else:
        form = UserLoginForm()

    context = {
        'title': 'Home - Login',
        'form': form
    }

    return render(request, 'users/login.html', context)


def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            if session_key:
                Cart.objects.filter(session_key=session_key).update(user=user)
            messages.success(request, f"{user.username} successfully registered and logged in 🥳")

            return HttpResponseRedirect(reverse('main:home'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Home - Registration',
        'form': form,
    }
    return render(request, 'users/registration.html', context)


def users_cart(request):
    return render(request, 'users/users_cart.html')


@login_required
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, f"Profile updated ✓")
            return HttpResponseRedirect(reverse('user:profile'))
    else:
        form = ProfileForm(instance=request.user)

    orders = (Order.objects.filter(user=request.user).prefetch_related(
        Prefetch(
            "orderitem_set",
            queryset=OrderItem.objects.select_related('product'),
        )
    ).order_by('-id')
    )

    context = {
        'title': 'Home - Profile',
        'form': form,
        'orders': orders
    }
    return render(request, 'users/profile.html', context)


@login_required
def logout(request):
    messages.success(request, f"Bye bye {request.user.username} 👋")
    auth.logout(request)
    return redirect(reverse('main:home'))

BurgerNymy/users/templates/users/login.html
{% extends "base.html"%}

{% load static %}
{% block title %}
{{title}}
{%endblock%}

{%block modal_cart%}
{% include 'includes/cart_button.html' %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                <h2 class="text-center mb-4">Authorization</h2>
                <form action="{% url 'user:login' %}" method="post">
                    {% csrf_token %}
                    {% if request.GET.next%}
                        <input type="hidden" name="next" value="{{request.GET.next}}">
                    {%endif%}
                    <div class="mb-3">
                        <label for="id_username" class="form-label">Username</label>
                        <input type="text" class="form-control" id="id_username" name="username" value="{% if form.username.value %}{{form.username.value}} {%endif%}" placeholder="Enter your Username" required>
                    </div>
                    <div class="mb-3">
                        <label for="id_password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="id_password" name="password" placeholder="Enter your password"
                               required>
                    </div>
                    <button type="submit" class="btn btn-dark btn-block">Log in</button>
                </form>
                <div class="mt-3">
                    <a href="#">Forgot password?</a> | <a href="{% url 'users:registration' %}">Create account</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Authorize with:</p>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'icons/google.svg'%}" alt="Catalog Icon" width="16" height="16">
                        Google
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'icons/facebook.svg'%}" alt="Catalog Icon" width="16" height="16">
                        Facebook
                    </a>
                    <a href="#" class="btn btn-dark">
                        <img class="mx-1" src="{% static 'icons/github.svg'%}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}

BurgerNymy/users/templates/users/logout.html
{% extends "base.html"%}

{% load static %}
{% block title %}
{{title}}
{%endblock%}
{% block content %}

{%endblock%}

BurgerNymy/users/templates/users/profile.html
{% extends "base.html"%}
{% load carts_tags %}


{% load static %}
{% block title %}
{{title}}
{%endblock%}

{%block modal_cart%}
{% include 'includes/cart_button.html' %}
{% endblock %}

{% block content %}

    <div class="container mt-5">
        <div class="row">
            <!-- Профиль с данными пользователя -->
            <div class="col-md-4">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">My profile</h3>
                    <form action="{% url 'user:profile' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-12 mb-3 text-center">
                                {%if user.image%}
                                <img src="{{ user.image.url }}"
                                     alt="Profile photo" class="img-fluid rounded-circle"
                                     style="max-width: 150px;">
                                {%else%}
                                <img src="{% static 'images/baseavatar.jpg'%}"
                                     alt="Profile photo" class="img-fluid rounded-circle"
                                     style="max-width: 150px;">
                                {%endif%}

                                <input type="file" class="form-control mt-3" id="id_image" name="image"
                                       accept="image/*">
                                {%if form.image.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.image.errors}}</div>
                                       {%endif%}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_first_name" class="form-label">First Name*</label>
                                <input type="text" class="form-control" id="id_first_name"
                                       name="first_name"
                                       placeholder="Enter your first name"
                                       value="{{ form.first_name.value }}"
                                        required>
                                {%if form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                       {%endif%}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_last_name" class="form-label">Last Name*</label>
                                <input type="text" class="form-control" id="id_last_name"
                                       name="last_name"
                                       placeholder="Введите вашу фамилию" value="{{ form.last_name.value }}"
                                       required>
                                {%if form.last_name.errors%}
                                       <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                       {%endif%}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_username" class="form-label">Username*</label>
                                <input type="text" class="form-control" id="id_username"
                                       name="username"
                                       placeholder="Enter your username" value="{{ form.username.value }}"
                                       required>
                                {%if form.username.errors%}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {%endif%}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                       name="email"
                                       placeholder="Enter your email *youremail@example.com" value="{{ form.email.value }}"
                                       required>
                                {%if form.email.errors%}
                                <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                                {%endif%}
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Save</button>
                    </form>
                </div>
            </div>
            <!-- Корзина -->
            {% user_carts request as carts %}

            <div class="col-md-8">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Cart</h3>
                    <div class="container">
                        <div class="flex flex-column" id="cart-items-container">
                        <!-- Разметка корзины -->
                            {% include "carts/includes/included_cart.html" %}
                        <!-- Закончилась разметка корзины -->
                            {%if carts%}
                                <a class="btn btn-dark" href="{% url 'orders:create_order' %}">
                                    Make order

                                </a>
                            {%endif%}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
                        <!-- Оформленные заказы -->
            <div class="col-md-12">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">My orders</h3>
                    <!-- Разметка заказов -->
                    <div class="container">

                        <div class="accordion accordion-flush" id="accordionExample">
                            {%for order in orders%}

                            <div class="accordion-item">
                                <h2 class="accordion-header" id="heading{{ order.id }}">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                            data-bs-target="#panelsStayOpen-collapse{{order.id}}" aria-expanded="false" aria-controls="panelsStayOpen-collapse{{order.id}}">
                                        Order № {{order.id}} - {{order.created_timestamp}} | Status:<strong class="mx-2">
                                        {{order.status}}</strong>
                                    </button>
                                </h2>
                                <div id="panelsStayOpen-collapse{{order.id}}" class="accordion-collapse collapse collapse">
                                    <div class="accordion-body">
                                        <table class="table table-dark table-hover">
                                            <thead>
                                            <tr>
                                                <th>Product</th>
                                                <th>Quantity</th>
                                                <th>Price</th>
                                                <th>Total price</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for item in order.orderitem_set.all %}
                                            <tr>
                                                <td><a class="text-white" href="{% url 'goods:product' item.product.slug %}">{{item.product.name}}</a></td>
                                                <td>{{item.quantity}}</td>
                                                <td>{{item.price}} $</td>
                                                <td>{{item.products_price}} $</td>

                                            </tr>
                                            {%endfor%}
                                            </tbody>
                                        </table>
                                        <div class="d-flex justify-content-between">
                                            <p><strong>Total:</strong></p>
                                            <p><strong>{{ order.total_price }} $</strong></p>

                                        </div>
                                    </div>
                                </div>
                            </div>
                            {%endfor%}
                        </div>
                    </div>
                    <!-- Закончилась разметка заказов -->
                </div>
            </div>

        </div>
    </div>
{%endblock%}

BurgerNymy/users/templates/users/registration.html
{% extends "base.html"%}

{% load static %}
{% block title %}
{{title}}
{% endblock %}

{%block modal_cart%}
{% include 'includes/cart_button.html' %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Registration</h2>
                <form action="{% url 'user:registration'%}" method="post">
                {% csrf_token %}

                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_firstName" class="form-label">First name*</label>
                            <input type="text" class="form-control" id="id_firstName"
                                   value = "{% if form.first_name.value %}{{form.first_name.value}}{%endif%}"
                                   name="first_name"
                                   placeholder="Enter your First name" required>

                            {%if form.first_name.errors%}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                            {%endif%}

                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_lastName" class="form-label">Last name*</label>
                            <input type="text" class="form-control" id="id_lastName"
                                   value = "{% if form.last_name.value %}{{form.last_name.value}}{%endif%}"
                                   name="last_name"
                                   placeholder="Enter your Last name" required>
                            {%if form.last_name.errors%}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                            {%endif%}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="username" class="form-label">Username*</label>
                            <input type="text" class="form-control" id="username"
                                   value = "{% if form.username.value %}{{form.username.value}}{%endif%}"
                                   name="username"
                                   placeholder="Enter your Username" required>
                            {%if form.username.errors%}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                            {%endif%}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_email" class="form-label">Email*</label>
                            <input type="email" class="form-control" id="id_email"
                                   value = "{% if form.email.value %}{{form.email.value}}{%endif%}"
                                   name="email"
                                   placeholder="Enter your email" required>
                            {%if form.email.errors%}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
                            {%endif%}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password1" class="form-label">Password*</label>
                            <input type="password" class="form-control" id="id_password1"
                                   name="password1"
                                   placeholder="Enter your password" required>
                            {%if form.password1.errors%}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
                            {%endif%}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_password2" class="form-label">Confirm the password*</label>
                            <input type="password" class="form-control" id="id_password2"
                                   name="password2"
                                       placeholder="Confirm the password" required>
                            {%if form.password2.errors%}
                            <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
                            {%endif%}
                        </div>
                    </div>
                    <button type="submit"
                            class="btn btn-dark btn-block">Registrate
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>
{%endblock%}

BurgerNymy/users/templates/users/users_cart.html
{%extends 'base.html'%}
{%load static %}
{% load carts_tags %}

{%block modal_cart%}
{% include 'includes/cart_button.html' %}
{% endblock %}

{%  block content%}
{% user_carts request as carts %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                <h3 class="text-center mb-4">Cart</h3>
                <div class="container" >
                    <div class="flex flex-column" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include 'carts/includes/included_cart.html'%}
                    <!-- Закончилась разметка корзины -->
                    {%if carts %}
                        <a class="btn btn-dark" href="{% url 'orders:create_order' %}">
                            Make order
                        </a>
                    {%endif%}

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{%endblock%}