BurgerNymy/BurgerNymy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from . import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('burgers.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""
www.site.com/admin/
www.site.com
www.site.com/about/
www.site.com/home/
www.site.com/catalog/






"""

BurgerNymy/carts/urls.py
# goods/urls.py

from django.urls import path
from carts import views

app_name = "carts"
urlpatterns = [
    path("cart_add/", views.cart_add, name="cart_add"),
    path("cart_change/", views.cart_change, name="cart_change"),
    path("cart_remove/", views.cart_remove, name="cart_remove"),
]

BurgerNymy/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'


urlpatterns = [
    path("create_order/", views.create_order, name="create_order"),
    ]

BurgerNymy/orders/models.py
from django.db import models
from goods.models import Products

from users.models import User


class OrderItemQueryset(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True,
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True,)
    phone_number = models.CharField(max_length=20,)
    requires_delivery = models.BooleanField(default=False,)
    delivery_address = models.TextField(null=True, blank=True,)
    payment_on_get = models.BooleanField(default=False,)
    is_paid = models.BooleanField(default=False,)
    status = models.CharField(max_length=50, default='In progress',)



    class Meta:
        db_table = "order"
        verbose_name = "Order"
        verbose_name_plural = "Orders"

    def __str__(self):
        return f"Order № {self.pk} | User {self.user.first_name} {self.user.last_name}"

    def total_price(self):
        return self.orderitem_set.all().total_price()


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, )
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, default=None)
    name = models.CharField(max_length=150, )
    price = models.DecimalField(max_digits=7, decimal_places=2,)
    quantity = models.PositiveIntegerField(default=0, )
    created_timestamp = models.DateTimeField(auto_now_add=True, )

    class Meta:
        db_table = "order_item"
        verbose_name = "Ordered product"
        verbose_name_plural = "Ordered products"

    objects = OrderItemQueryset().as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"Product {self.name} | Order № {self.order.pk}"

BurgerNymy/orders/forms.py
import re
from django import forms


class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True),
        ],
    )
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(
        choices=[
            ("0", 'False'),
            ("1", 'True'),
        ],
    )

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        if not data.isdigit():
            raise forms.ValidationError("Use only digits")

        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError("Incorrect input, follow format: XXX-XXX-XX-XX")

        return data

    # first_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите ваше имя",
    #         }
    #     )
    # )

    # last_name = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Введите вашу фамилию",
    #         }
    #     )
    # )

    # phone_number = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             "class": "form-control",
    #             "placeholder": "Номер телефона",
    #         }
    #     )
    # )

    # requires_delivery = forms.ChoiceField(
    #     widget=forms.RadioSelect(),
    #     choices=[
    #         ("0", False),
    #         ("1", True),
    #     ],
    #     initial=0,
    # )

    # delivery_address = forms.CharField(
    #     widget=forms.Textarea(
    #         attrs={
    #             "class": "form-control",
    #             "id": "delivery-address",
    #             "rows": 2,
    #             "placeholder": "Введите адрес доставки",
    #         }
    #     ),
    #     required=False,
    # )

    # payment_on_get = forms.ChoiceField(
    #     widget=forms.RadioSelect(),
    #     choices=[
    #         ("0", 'False'),
    #         ("1", 'True'),
    #     ],
    #     initial="card",
    # )

BurgerNymy/orders/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render

from carts.models import Cart

from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem


@login_required
def create_order(request):
    if request.method == 'POST':
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if cart_items.exists():
                        # Создать заказ
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data['phone_number'],
                            requires_delivery=form.cleaned_data['requires_delivery'],
                            delivery_address=form.cleaned_data['delivery_address'],
                            payment_on_get=form.cleaned_data['payment_on_get'],
                        )
                        # Создать заказанные товары
                        for cart_item in cart_items:
                            product=cart_item.product
                            name=cart_item.product.name
                            price=cart_item.product.sell_price()
                            quantity=cart_item.quantity


                            if product.quantity < quantity:
                                raise ValidationError(f'Недостаточное количество товара {name} на складе\
                                                       В наличии - {product.quantity}')

                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()

                        # Очистить корзину пользователя после создания заказа
                        cart_items.delete()

                        messages.success(request, 'Заказ оформлен!')
                        return redirect('user:profile')
            except ValidationError as e:
                messages.success(request, str(e))
                return redirect('cart:order')
    else:
        initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            }

        form = CreateOrderForm(initial=initial)

    context = {
        'title': 'Home - Create order',
        'form': form,
        'orders': True,
    }
    return render(request, 'orders/create_order.html', context=context)

BurgerNymy/orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
        <div class="container">
            <h3 class="text-center mb-4">Выбранные товары</h3>
            <div class="container" id="cart-items-container">
                <!-- Разметка корзины -->
                {%user_carts request as carts %}

                {% include 'carts/includes/included_cart.html' %}
                <!-- Закончилась разметка корзины -->
            </div>
        </div>
        <!-- Детали заказа -->
        <div class="container">
            <h3 class="text-center">Детали заказа</h3>
            <div class="card mb-3">
                <div class="card-body">
                    <form action="{% url 'orders:create_order' %}" method="POST">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">First Name*:</label>
                                <input type="text" class="form-control" id="id_first_name" name="first_name"
                                value = "{% if form.first_name.value %}{{form.first_name.value}}{%endif%}" required>
                                {%if form.first_name.errors%}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.first_name.errors}}</div>
                                {%endif%}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Last Name*:</label>
                                <input type="text" class="form-control" id="id_last_name" name="last_name"
                                       value = "{% if form.last_name.value %}{{form.last_name.value}}{%endif%}" required>
                                {%if form.last_name.errors%}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.last_name.errors}}</div>
                                {%endif%}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_phone_number" class="form-label">Telephone Number*:</label>
                                <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                    placeholder="Format: XXX-XXX-XX-XX"
                                    required>
                                {%if form.phone_number.errors%}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.phone_number.errors}}</div>
                                {%endif%}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label for="delivery" class="form-label">Delivery method: </label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                        id="id_requires_delivery" value="1" checked>
                                    <label class="form-check-label" for="id_requires_delivery">Delivery</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="requires_delivery"
                                        id="id_requires_delivery" value="0">
                                    <label class="form-check-label" for="id_requires_delivery">Pickup</label>
                                </div>
                            </div>
                            <div class="mb-3" id="deliveryAddressField">
                                <label for="id_delivery_address" class="form-label">Delivery address:</label>
                                <textarea class="form-control" id="id_delivery_address"
                                    name="delivery_address" rows="2"
                                    value = "{% if form.last_name.value %}{{form.last_name.value}}{%endif%}"></textarea>
                                {%if form.delivery_address.errors%}
                                    <div class="alert alert-danger alert-dismissible fade show">{{form.delivery_address.errors}}</div>
                                {%endif%}
                            </div>
                            <div class="col-md-12 mb-3">
                                <label class="form-label">Payment method: </label>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                        id="id_payment_on_get" value="0" checked>
                                    <label class="form-check-label" for="id_payment_on_get">Cart</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="payment_on_get"
                                        id="id_payment_on_get" value="1">
                                    <label class="form-check-label" for="id_payment_on_get">Cash/Cart on delivery</label>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-dark">Make order</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}