BurgerNymy/BurgerNymy/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from . import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('burgers.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""
www.site.com/admin/
www.site.com
www.site.com/about/
www.site.com/home/
www.site.com/catalog/






"""

BurgerNymy/carts/urls.py
# goods/urls.py

from django.urls import path
from carts import views

app_name = "carts"
urlpatterns = [
    path("cart_add/", views.cart_add, name="cart_add"),
    path("cart_change/", views.cart_change, name="cart_change"),
    path("cart_remove/", views.cart_remove, name="cart_remove"),
]

BurgerNymy/goods/urls.py
# goods/urls.py

from django.urls import path
from goods import views

app_name = "goods"
urlpatterns = [
    path("search/", views.catalog, name="search"),
    path("<slug:category_slug>/", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product"),

]

BurgerNymy/users/urls.py
# burgers/urls.py

from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name='registration'),
    path("profile/", views.profile, name='profile'),
    path("logout/", views.logout, name='logout'),
    path("users_cart/", views.users_cart, name='users_cart'),

    # Add other paths as needed
]

BurgerNymy/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load goods_tags %}
<link rel="stylesheet" href="{% static 'burgers/css/bootstrap/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'burgers/css/my_css.css' %}">


<html lang="en">
  <head>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>
      {% block title %}
        Django App
      {% endblock %}
    </title>
    <link rel="icon" href="{% static 'images/hamburger.png' %}" type="image/x-icon">
    <link rel="stylesheet" id="fname" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" />
<!--    <link rel="stylesheet" href="{% static 'myapp/css/styles.css' %}">-->
  </head>
  <body>
<!--  Nav bar-->
    <nav  class="navbar navbar-expand-lg navbar-light bg-light ">
      <a class="navbar-brand" href="/">NyMyBu</a>
      <button class="navbar-toggler " type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Menu
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              {% tag_categories as categories%}
              {% for category in categories %}
              <li><a class="dropdown-item" href="{% url 'catalog:index' category.slug %}">{{ category.name }}</a></li>
              {% endfor %}
            </ul>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="/about">About Us</a>
          </li>
          {%if user.is_authenticated%}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              My Profile
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'users:profile' %}">Personal account</a></li>
              {%if user.is_staff or user.is_admin %}
              <li><a class="dropdown-item" href="/admin">Admin</a></li>
              {%endif%}
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </li>
          {% endif %}
        </ul>
      </div>

      <form class="d-flex" role="search" action="{% url 'catalog:search' %}" method="get">
          <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

      {%if not user.is_authenticated %}
      <a class="nav-item mr-3 nav-link p-3" href="{% url 'users:login' %}">Login</a>
      {%endif%}
      {% block modal_cart %}{%endblock%}
    </nav>

    <div class="container">
      <div class="row justify-content-center ">
        <div class="col-9">
          {% include "includes/notifications.html" %}
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
<script src="{% static 'js/jquery/jquery-3.7.0.min.js' %}"></script>
<script src="{% static 'js/jquery-ajax.js'%}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js'  %}"> </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>